# Generated by Django 3.2.8 on 2022-10-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=20)),
                ('u_password', models.CharField(max_length=255)),
                ('ticket', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'p427_user',
            },
        ),
    ]
